version: "3"
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.3.1
    volumes:
      - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml"
      - "./filebeat/logs/:/log/"
  logstash:
    image: docker.elastic.co/logstash/logstash:7.3.1
    ports:
      - "9600:9600" # Default logstash port
      - "5044:5044" # Beats input port
    volumes:
      - "./logstash/pipeline/:/usr/share/logstash/pipeline/"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200" # Default api port
      - "9300:9300" # Default communication port
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    ports:
      - "5601:5601" # Default web interface port
